name = "FormatSpecimens"
uuid = "3372ea36-2a1a-11e9-3eb7-996970b6ffbd"
authors = ["Ben J. Ward <benjward@protonmail.com"]
version = "1.0.0"

[deps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
