name = "FormatSpecimens"
uuid = "3372ea36-2a1a-11e9-3eb7-996970b6ffbd"
authors = ["Ben J. Ward <benjward@protonmail.com"]
version = "1.2.0"

[deps]
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[compat]
TOML = "1.0.3"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
