[[valid]]
filename = "cysprot.p*"
origin = "BioPython"
tags = ["protein"]
comments = ["made with BLAST v2.3.0+ from ../FASTA/cysprot.fasta, requires 3 files (.pin, .phr, .psq)"]

[[valid]]
filename = f002.n*
origin = "BioPython"
tags = ["dna"]
comments = ["made with BLAST v2.3.0+ from ../FASTA/f002.fasta, requires 3 files (.nin, .nhr, .nsq)"]

[[valid]]
filename = "cysprot.xml"
origin = "BioPython"
tags = ["protein"]
comments = ["made with BLAST v2.3.0+ blasting ./FASTA/cysprot.fasta against db cysprot"]

[[valid]]
filename = "f002.xml"
origin = "BioPython"
tags = ["protein"]
comments = ["made with BLAST v2.3.0+ blasting ./FASTA/f002.fasta against db f002"]
